# Numpy Tutorial - Google Developments


[Numpy](https://numpy.org/doc/stable/index.html) is a Python library for creating and manipulating matrices, the main data structure used by ML algorithms. [Matrices](https://en.wikipedia.org/wiki/Matrix_(mathematics)) are mathematical objects used to store values in rows and columns. 
Python calls matrices *lists*, NumPy calls them *arrays* and TensorFlow calls them *tensors*. Python represents matrices with the [list data type](https://docs.python.org/3/library/stdtypes.html#lists).


In [4]:
!pip install numpy


In [5]:
import numpy as np

#Trabalhando com uma dimensão
one_dimension = np.array([1.3, 2.4, 6, 7, 8])
print(one_dimension)

#Criando uma matriz 3x2
two_dimensions = np.array([[1, 2], [3, 4], [5, 6]])
print(two_dimensions)

[1.3 2.4 6.  7.  8. ]
[[1 2]
 [3 4]
 [5 6]]


## Populate arrays with sequences of numbers

In [6]:
sequence_of_integers = np.arange(5, 11)
print(sequence_of_integers)

[ 5  6  7  8  9 10]


Notice that np.arange generates a sequence that includes the lower bound (5) but not the upper bound (12). 

## Populate arrays with random numbers

In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6,))
print(random_integers_between_50_and_100)

[ 71  75  64 100  89  92]


##### To create random floating-point values between 0.0 and 1.0, call np.random.random. For example:

In [12]:
random_floats = np.random.random(size=(6,))
print(random_floats)

[0.16311812 0.67607344 0.73967529 0.16180615 0.93408973 0.79687229]


## Operations Working array

In [13]:
# Arrays com numpys são mutaveis e muito parecido com as operações que podemos realizar nas listas

print(random_floats[0])
print("******************************")
random_floats[0] = 1.01
print(random_floats)

0.16311812481321142
******************************
[1.01       0.67607344 0.73967529 0.16180615 0.93408973 0.79687229]


In [19]:
# Consigo realizar fatiamento com arrays

a = np.array([1, 2, 3, 5, 6, 7, 8, 9])
b = a[:]
print(b) # printa a copia de a

print(a[:3]) # printa os três primeiros do array

[1 2 3 5 6 7 8 9]
[1 2 3 5 6 7 8 9]


In [27]:
#Ainda sobre fatiamentos com arrays

x = np.array([10, 12, 13, 14])
y = x[2:]
y[0] = 60
print(y)
print(x)

print("***********************")
#Para acessar elementos de uma matriz com array do Numpy, podemos fazer dessa forma:

z  = np.array([
    [1, 2, 3, 4,],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])
print(z)

print(z[1, 1])

[60 14]
[10 12 60 14]
***********************
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6


## Array attributes

This section covers the ndim, shape, size, and dtype attributes of an array.

In [28]:
print(z.ndim) # Retorna o número de dimensões da matriz

2


In [29]:
print(z.shape) # linha x colunas

(3, 4)


In [30]:
print(z.size)

12


In [31]:
print(z.dtype)

int64


## How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [35]:
zeros_matrix = np.zeros(3)
print(zeros_matrix)

[0. 0. 0.]


In [37]:
ones_matrix = np.ones(3)
print(ones_matrix)

[1. 1. 1.]


In [47]:
elements_matrix = np.empty(5)
print(elements_matrix)

[1.3 2.4 6.  7.  8. ]


In [48]:
numbers_space = np.linspace(0, 10, num=5) #Pode ser muito importante! Usa espaços lineares para um determinado intervalo de números
print(numbers_space)

[ 0.   2.5  5.   7.5 10. ]
